#define LANG_en
#define Estado "Status"
#define LigaDesliga "On/Off"
#define Desligar "Off"
#define Ligar "On"
#define Avisos "Notes"
#define Aviso "Note"
#define Feriado "Holyday"
#define Fixo "Fix"
#define Feriados "Holydays"
#define Aniversarios "Birthdays"
#define Arquivos "Files"
#define Tamanho "Size"
#define Programacao "Schedule"
#define Configuracao "Configuration"
#define Usuarios "Users"
#define Reiniciar "Reboot"
#define Ligado "On"
#define Desligado "Off"
#define Senha "Password"
#define Nivel "Level"
#define Mudarparatv "Change Input to TV"
#define Mudarparavga "Change Input to VGA"
#define Memoria "Memory"
#define Versao "Version"
#define Temperatura "Temperature"
#define Senhaintegracao "Integration Password"
#define SensorDeTemperaturaenc "Temperature sensor found"
#define SensorDeTemperaturanaoenc "Temperature sensor not found"
#define Patrimonio "Tag"
#define Dia "Day"
#define Mes "Month"
#define Usuario "User"
#define Nao "No"
#define Sim "Yes"
#define Erro "Erro"
#define Compilado "Compiled"
#define Dom "Sun"
#define Seg "Mon"
#define Ter "Tue"
#define Qua "Wed"
#define Qui "Thu"
#define Sex "Fri"
#define Sab "Sat"
#define Solicitado "Turning"
#define Hora "Hour"
#define Minuto "Minute"
#define Ativo "Enabled"
#define CorFrente "Front Color"
#define CorFundo "Back Color"
#define Branco "White"
#define Preto "Black"
#define Vermelho "Red"
#define Verde "Green"
#define Quebradelinha "Line Break"
#define Salvar "Submit"
#define Entrada "Input"
#define Nome "Name"
#define Mostrarnatv "Show on TV"
#define AdicionarAviso "To add Note, use the last line"
#define RemoverAviso "To delete Note, left blank"
#define AdicionarProg "To add Schedule, use the last line"
#define RemoverProg "To delete Schedule, left blank"
#define Sensortemp "Temperature Sensor"
#define PinosVGA "VGA Pins"
#define PinoLDR "LDR Pin"
#define PinoIR "IR Pin"
#define Reiniciando "Rebooting"
#define MudarHDMI "Change to HDMI"
#define MudarVGA "Change to VGA"
#define MudarTV "Change to TV"
#define Reiniciar "Reboot"
#define Errcorfrentefundo "Atenção: cor de frente igual a cor de fundo no Aviso"
#define AdicionarUsuario "To add User, use the last line"
#define NomedoEsp32 "Esp32 Name"
#define mDNS "mDNS"
#define HabilitarVga "Clique para Habilitar a saida VGA"
#define DesabilitarVga "Click to disable VGA out"
#define AdicionarFeriado "To add holyday, use the last line, to delete, left blank"
#define Erroarquivoprogf "Error opening file programacaof"
#define Executandoprog "Schedule"
#define Arquivoprogsalvo "File programacaof saved"
#define Bytesusados "Used Bytes"
#define Arquivo "File"
#define E "and"
#define Cursos "Courses"
