#define LANG_pt
#define Estado "Estado"
#define LigaDesliga "Liga/Desliga"
#define Desligar "Desligar"
#define Ligar "Ligar"
#define Avisos "Avisos"
#define Feriados "Feriados"
#define Feriado "Feriado"
#define Fixo "Fixo"
#define mDNS "mDNS"
#define Sim "Sim"
#define Nao "N&atilde;o"
#define NomedoEsp32 "Nome do Esp32"
#define Sensortemp "Sensor de Temperatura"
#define PinosVGA "Pinos VGA"
#define PinoLDR "Pino LDR"
#define PinoIR "Pino IR"
#define Aniversarios "Anivers&aacute;rios"
#define Arquivos "Arquivos"
#define Programacao "Programa&ccedil;&atilde;o"
#define Configuracao "Configura&ccedil;&atilde;o"
#define Reiniciar "Reiniciar"
#define Reiniciando "Reiniciando"
#define Dom "Dom"
#define Seg "Seg"
#define Ter "Ter"
#define Qua "Qua"
#define Qui "Qui"
#define Sex "Sex"
#define Sab "Sáb"
#define CorFrente "Cor Frente"
#define CorFundo "Cor Fundo"
#define Branco "Branco"
#define Preto "Preto"
#define Vermelho "Vermelho"
#define Verde "Verde"
#define Quebradelinha "Quebra de Linha"
#define Salvar "Salvar"
#define Entrada "Entrada"
#define Nome "Nome"
#define Mostrarnatv "Mostrar na TV"
#define Dia "Dia"
#define RemoverAviso "Para Apagar aviso, deixe a linha em branco"
#define BytesUsados "Bytes Usados"
#define Arquivo "Arquivo"
#define AdicionarAviso "Adicionar Aviso"
#define Tamanho "Tamanho"
#define DesabilitarVga "Desabilitar VGA"
#define Solicitado "Solicitado"
#define Desligartv "Desligar TV"
#define Ligartv "Ligar TV"
#define HabilitarVga "Habilitar VGA"
#define MudarTV "Mudar para TV"
#define MudarVGA "Mudar para VGA"
#define MudarHDMI "Mudar para HDMI"
#define Arquivoprogsalvo "Arquivo programacaof salvo"

#define Erroarquivoprogf "Erro no arquivo programacaof"
#define AdicionarProg "Adicionar Programacao"
#define RemoverProg "Apagar Programacao"
#define Senha "Senha"
#define Nivel "Nivel"
#define AdicionarUsuario "Adicionar Usuario"
#define SensorDeTemperaturanaoenc "Sensor de Temperatura nao encontrado"
#define SensorDeTemperaturaenc "Sensor de Temperatura encontrado"
#define Executandoprog "Executando Programacao"
#define Bytesusados "Bytes Usados"
#define AdicionarFeriado "Para adicionar feriado, utilize a ultima linha" 
#define E "e"
#define Cursos "Cursos"
#define Errcorfrentefundo "Atenção: cor de frente igual a cor de fundo no Aviso"
#define Ligado "Ligado"
#define Aviso "Aviso"
#define Memoria "Mem&oacute;ria"
#define Versao "Vers&atilde;o"
#define Temperatura "Temperatura"
#define Usuarios "Usu&aacute;rios"
#define Senhaintegracao "Senha integra&ccedil;&atilde;o"
#define Patrimonio "Patrim&ocirc;nio"
#define Mes "M&ecirc;s"
#define Usuario "Usu&aacute;rio"
#define Nao "N&atilde;o"
#define Ativo "Ativo"
#define Hora "Hora"
#define Minuto "Minuto"
#define Entrada "Entrada"
#define Desligado "Desligado"
#define Compilado "Compilado"
#define Nome "Nome"
#define Avisodeletar "Deixe em branco para deletar"
#define Salvar "Salvar"
